
import NavBar from '@/components/NavBar';
import type { Metadata } from 'next';
import { cookies } from "next/headers";
import { redirect } from "next/navigation";



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const cookieStore = cookies();

  const cookie = cookieStore.get('t-cookie');
  console.log(`isnide of layout ${cookie?.value}`);

  if(cookie !== undefined ) {

        return (
          <html lang="en">
            <body className="{inter.className} font-serif" > 
            <div className="sticky top-0 z-50"> 
                <NavBar />
                {children}
            </div>
                
            </body>
          </html>
        )
      
    }
  

  redirect('/');
  
}
