import './globals.css'
import type { Metadata } from 'next'
//import { Inter } from 'next/font/google';
import RecoidContextProvider from "./recoilContextProvider";


//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (

    <html lang="en">
      <body className="{inter.className} font-serif" >
        <RecoidContextProvider>
          {children}

        </RecoidContextProvider>
        
      </body>
    </html>
  )
}
