import '../globals.css'
import type { Metadata } from 'next';
import { cookies, headers } from "next/headers";
import { redirect } from "next/navigation";
import { useSetRecoilState } from 'recoil';

import { getUserFromJWT } from '@/lib/getUserFromJWT';
import { userDetails, userDetailsType } from '@/lib/zodTypes';
import { UserAtom } from '@/recoil/atoms/userAtoms';
import NavBar from '@/components/NavBar';
import Result from '@/components/search/Result';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const cookieStore = cookies();

  const cookie = cookieStore.get('t-cookie');
  console.log(`isnide of layout ${cookie?.value}`);

  if(cookie !== undefined ) {

        return (
          <html lang="en">
            <body className="{inter.className} font-serif" > 
              <div className="sticky top-0 z-50"> 
                  <NavBar />
                  <div className="relative flex flex-col items-center justify-center m-3">
                    <Result />
                  </div>

                  {children}
              </div>
            </body>
          </html>
        )
      
    }
  redirect('/');
  
}
